baseURL = "https://lucasmarques.dev/"
languageCode = "pt-br"

theme = "hugo-goa"

author = "Lucas Marques"
title = "Lucas Marques"

googleAnalytics = "UA-115778035-1"
enableRobotsTXT = true

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"


## Site Settings
[params]
author = "Lucas Marques"
intro = "Desenvolvedor Web"
description = "Desenvolvedor Web com foco nas linguagens Go e PHP"
authorimage = "me.jpg"
dateformat = "Jan 2, 2006"
errormessage = "Desculpa! Essa página não existe. Pode ter sido removido ou movido para uma nova seção no site."

## Site Meta Settings
[params.meta]
description = "Desenvolvedor Web com foco nas linguagens Go e PHP"
keywords = "blog,goa,hugo,developer,desenvolvedor,web,software,engineer,go,golang,php"

## Social Accounts
[params.social]
twitter = "lucas_marques"
github = "lucasmarques73"
linkedin = "lucasmarques73"
email = "lucasmarques73@hotmail.com"

## Extras
[params.extra]
copyright = "© 2019. Lucas Marques. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)." 
poweredby = true
hightlightjs = true
socialmarkup = true


[[menu.main]]
    name = "home"
    weight = 100
    url = "/"
[[menu.main]]
    name = "posts"
    weight = 200
    url = "/posts/"
[[menu.main]]
    name = "Projetos"
    weight = 300
    url = "/projects/"
[[menu.main]]
    name = "Sobre mim"
    weight = 400
    url = "/about/"