# baseURL = "http://lucasmarques73.com.br/"
# localhost
baseURL = "https://lucasmarques73.com.br/"
languageCode = "pt-br"

theme = "hugo-goa"

author = "Lucas Marques"
title = "Lucas Marques"

googleAnalytics = "UA-115778035-1"
enableRobotsTXT = true

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"


## Site Settings
[params]
author = "Lucas Marques"
intro = "Desenvolvedor Web"
description = "Desenvolvedor Web com foco nas linguagens Go e PHP"
authorimage = "me.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Desenvolvedor Web com foco nas linguagens Go e PHP"
keywords = "blog,goa,hugo,developer,desenvolvedor,web,software,engineer,go,golang,php"

## Social Accounts
[params.social]
twitter = "lucas_marques"
github = "lucasmarques73"
linkedin = "lucasmarques73"
email = "lucasmarques73@hotmail.com"

## Extras
[params.extra]
copyright = "© 2018. Lucas Marques." 
poweredby = true
hightlightjs = true


[[menu.main]]
    name = "posts"
    weight = 100
    url = "/posts/"
[[menu.main]]
    name = "Projetos"
    weight = 200
    url = "/projects/"
[[menu.main]]
    name = "Sobre mim"
    weight = 300
    url = "/about/"