version: '3'

services:
  hugo:
    build: .
    volumes:
      - ./lucasmarques73:/var/www/html/lucasmarques73
      - ./entrypoint.sh:/var/www/html/lucasmarques73/entrypoint.sh
    ports:
      - 1313:1313
    restart: unless-stopped
    entrypoint: /bin/sh /var/www/html/lucasmarques73/entrypoint.sh
  homepage:
    image: nginx:1.15.2-alpine
    volumes:
      - ./lucasmarques73/public:/var/www/html/lucasmarques73
      - ./nginx/homepage.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - hugo