version: '3'

services:
  hugo:
    build: docker/.
    volumes:
      - .:/var/www/html/lucasmarques73
    ports:
      - 1313:1313
    restart: unless-stopped
    entrypoint: /bin/sh /var/www/html/lucasmarques73/docker/entrypoint.sh