# baseURL = "http://lucasmarques73.com.br/"
# localhost
baseURL = "http://localhost/"
languageCode = "pt-br"

theme = "hugo-goa"

author = "Lucas Marques"
title = "Lucas Marques"

googleAnalytics = "UA-115778035-1"
enableRobotsTXT = true

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

## Site Settings
[params]
author = "Lucas Marques"
intro = "Desenvolvedor Web"
description = ""
authorimage = "me.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Diario de um desenvolvedor web"
keywords = "diario,blog,goa,hugo,developer,desenvolvedor,web"

## Social Accounts
[params.social]
github = "lucasmarques73"
linkedin = "lucasmarques73"
twitter = "lucas_marques"
email = "lucasmarques73@hotmail.com"

## Extras
[params.extra]
copyright = "© 2018. Lucas Marques." 
poweredby = true
hightlightjs = true


[[menu.main]]
    name = "blog"
    weight = 100
    url = "/blog/"
[[menu.main]]
    name = "Projetos"
    weight = 200
    url = "/projects/"
[[menu.main]]
    name = "Sobre mim"
    weight = 300
    url = "/about/"